### ISSUE TITLE
Implement API tests library - MVP

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/ScAPI#1]
## Description
The goal of this Epic is to find out how to implement API tests using non UI based solution.
The solution will be new tool for design of tests.

Named tasks are outline which can be changed during time of API test development.

### Tasks
- [x] https://github.com/absa-group/AUL-test/issues/2
- [x] https://github.com/absa-group/AUL-test/issues/4
- [x] https://github.com/absa-group/ScAPI/issues/6
- [x] https://github.com/absa-group/ScAPI/issues/7
- [x] https://github.com/AbsaOSS/ScAPI/issues/3
- [x] https://github.com/AbsaOSS/ScAPI/issues/5
- [x] https://github.com/AbsaOSS/ScAPI/issues/6
- [x] https://github.com/AbsaOSS/ScAPI/issues/11
- [x] https://github.com/AbsaOSS/ScAPI/issues/15
- [x] https://github.com/AbsaOSS/ScAPI/issues/20
- [x] https://github.com/AbsaOSS/ScAPI/issues/17
- [x] https://github.com/AbsaOSS/ScAPI/issues/18
- [x] https://github.com/AbsaOSS/ScAPI/issues/28
- [x] #33
- [x] #35
- [x] #37
