### ISSUE TITLE
Introduce test before and after jsons file and related logic

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/ScAPI#3]
```[tasklist]
### Tasks
- [x] Add json file validation
- [x] Add json file parsing
- [x] Add json file reference replacing - environment ones
- [x] Add integration with suite logic
```
