### ISSUE TITLE
Introduce function json related logic

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/ScAPI#4]
```[tasklist]
### Tasks
- [ ] Add json file validation
- [ ] Add json file parsing
- [ ] Add reference replacing logic - environment ones
- [ ] Add reference replacing logic - suite files
- [ ] Add reference replacing logic - before and after files
- [ ] Add integration with suite logic
- [ ] Add integration with before and after logic
```
